// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl9QIQLKuuWAD67zn-voE2ZQGL0KpAGg0',
    appId: '1:471373690820:android:257b438bf7b68d6e9c9691',
    messagingSenderId: '471373690820',
    projectId: 'democratic-dj-fe97d',
    storageBucket: 'democratic-dj-fe97d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWvCgvorSMD56nenJj-5RAkmqBMTiICcA',
    appId: '1:471373690820:ios:10d6fc9b3d91ff219c9691',
    messagingSenderId: '471373690820',
    projectId: 'democratic-dj-fe97d',
    storageBucket: 'democratic-dj-fe97d.firebasestorage.app',
    iosBundleId: 'com.uniraticdj.democraticapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Tuut7lcXToZbF1FsNVWOffHWq6U7IEI',
    appId: '1:471373690820:web:cf100b83cc97ebd39c9691',
    messagingSenderId: '471373690820',
    projectId: 'democratic-dj-fe97d',
    authDomain: 'democratic-dj-fe97d.firebaseapp.com',
    storageBucket: 'democratic-dj-fe97d.firebasestorage.app',
    measurementId: 'G-TDK3QZH3YT',
  );

}